list1=[]
list2=[]
list1.append(4.5)
list1.append(3.4)
list1.extend([8.7, 1.3])
list2.append(14.5)
list2.append(3.4)
list2.extend([8.7, 11.3])
list1.insert(1,100)
list1.insert(3,100)
list2.insert(0,200)
list2.insert(2,200)
print("Исходные списки:")
print(list1)
print(list2)
del list1[0]
del list2[0]
list1.remove(100)
list2.remove(200)
print("\nПосле удалений:")
print(list1)
print(list2)
slist1=set(list1)
slist2=set(list2)
slist1_and_slist2=slist1&slist2
print("\nУникальные элементы:")
print(list1)
print(list2)
print("общие:", slist1_and_slist2)
plus=list1+list2
plus_asc=sorted(plus)
plus_desc=sorted(plus, reverse=True)
sr_ar=sum(plus[1::2])/len(plus[1::2])
import math
sr_geom=math.prod(plus[0::2])**(1/len(plus[0::2]))
plus_max=max(plus)
plus_min=min(plus)
print("\nИтоговые:")
print("3-й:", plus)
print("Сортировка (возр.):", plus_asc)
print("Сортировка (убыв.):", plus_desc)
print(f"Ср. арифм. = {sr_ar:.2f}, ср. геометр. = {sr_geom:.2f}")
print("Макс. и мин.:", plus_max, plus_min)